services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ms_product
    ports:
      -   "3306:3306"
    networks:
      - my-network

networks:
  my-network:3306
